---
- name: Deploy to S3
  hosts: localhost
  vars:
    domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
    bucket_policy:
      Version: 2012-10-17
      Statement:
      - Sid: PublicReadGetObject
        Effect: Allow
        Principal: "*"
        Action: s3:GetObject
        Resource: arn:aws:s3:::{{ domain_name }}/*
  tasks:
  - name: Primary bucket | Create
    s3_bucket:
      name: "{{ domain_name }}"
      state: present
      policy: "{{ bucket_policy | to_json }}"

  - name: Primary bucket | Sync
    s3_sync:
      bucket: "{{ domain_name }}"
      file_root: ../dist
      file_change_strategy: checksum
      permission: public-read

  - name: Primary bucket | Configure website
    s3_website:
      name: "{{ domain_name }}"
      state: present

  - name: Secondary bucket | Create
    s3_bucket:
      name: www.{{ domain_name }}
      state: present

  - name: Secondary bucket | Configure website (redirect to primary)
    s3_website:
      name: www.{{ domain_name }}
      state: present
      redirect_all_requests: "{{ domain_name }}"
